### ISSUE TITLE
Update Wheel Piece

### ISSUE THREAD

**Issue by miff** [herbou/Unity_PickerWheelUI#1]
Hi, what will be "safe" way to update `Amount` text?

For example you have bet multiplier and want to update label of amount?

I'm already tried to call `Generate()` method, but not sure is it right way.

Thanks

**Comment by herbou** [comment]
You have to change it in tge wheelPieces array and the Ui too

**Comment by miff** [comment]
Thanks, I'm new to C# what is `tge`?

**Comment by herbou** [comment]
sorry it's just typing mistake. it's "the"

**Comment by miff** [comment]
Oh, ok :)
